### ISSUE TITLE
Keep getting TypeError when connecting

### ISSUE THREAD

**Issue by Mafiti** [jsplumb/community-edition#1044]
hello guys, i will keep getting TypeError: Cannot read properties of undefined (reading 'x') when connecting, how do i fix this problem, or provide some ideas  to solve this problem. thx!

<img width="1205" alt="image" src="https://github.com/jsplumb/community-edition/assets/37899813/876c75a2-7804-4724-bea4-618f74bebf55">

**Comment by ls1106** [comment]
Hello, may I ask how you resolved the issue of Unsught TypeError: Cannot read properties of undefined (reading 'x')?
