### ISSUE TITLE
How to use @jsplumbtoolkit/labels

### ISSUE THREAD

**Issue by Hazlank** [jsplumb/community-edition#1061]
@jsplumbtoolkit version: 5.12
Hi, I wan't make overlay labels can drag then change there position,so i import @jsplumbtoolkit/labels and use it like
```js
import { LabelDragManager } from '@jsplumbtoolkit/labels';
....
const view = {
	edges: {
		[DEFAULT]: {
			overlays: [
				{
					type: LabelOverlay.type,
					options: {
					id: 'label',
					label: 'Text',
				},
			}]
		} 
	}
}
....
useEffect(() => {
	if (surface) {
		new LabelDragManager({surface})
	}
})
```

When i drag labels, nothing happend, the surface className is `painning`. is any options i lost setting?

**Comment by Hazlank** [comment]
@sporritt is @jsplumbtoolkit/labels can not support @jsplumbtoolkit5.x?

```js
constrainFunction: function e(t, n) {
        var o = n._jsPlumb.component.getConnector(),
          a = {
            left: parseInt(o.canvas.style.left, 10),
            top: parseInt(o.canvas.style.top, 10),
          },
          c = t.x - a.left,
          s = t.y - a.top,
          f = o.paintExtents.xmin < 0 ? -o.paintExtents.xmin : 0,
          u = o.paintExtents.ymin < 0 ? -o.paintExtents.ymin : 0;
        var l = o.findSegmentForPoint(c - f, s - u);
        return { x: l.x + a.left + f, y: l.y + a.top + u };
}
```

I see some functions that are not present in @jsplumb/core.

**Comment by Hazlank** [comment]
@sporritt I modify code `n._jsPlumb.component.getConnector` to `n.jtk.overlay.component.connector`, it seems like work.
```js
function m(e, t) {
  var n = e.connector.bounds.xmin < 0 ? -e.connector.bounds.xmin : 0;
  var r = e.connector.bounds.ymin < 0 ? -e.connector.bounds.ymin : 0;
  var i = t.x - e.connectorOffset.x;
  var o = t.y - e.connectorOffset.y;
  var a = e.connector.findSegmentForPoint(i - n, o - r);
  return a.connectorLocation;
}
```
But findSegmentForPoint function return `connectorLocation` value is `Infinity`.
How to calculate label drag location

**Comment by sporritt** [comment]
@Hazlank This issue tracker is for the community edition, not the Toolkit edition.  I've replied to you over email - we should continue the discussion there. This issue will be deleted.
