### ISSUE TITLE
Wrap Connectors with a div/span 

### ISSUE THREAD

**Issue by nicoloboschi** [jsplumb/community-edition#362]
I'm using https://github.com/niklasvh/html2canvas library for export a jsplumb diagram
The library does not provide support for SVG absolute positioned images, as the JSplumb connectors are, but wrapping them with a absolute span (or div) it works as expected 

I was peeking in jsplumb source code and I've seen that there is a param 'useDivWrapper' for SVG elements, but it is not used for connectors rendering, there is a way (hopefully not dirty) to pass this param when creating the connector?

Alternatevely, I was thinking to manually wrap the svg elements but I would like to avoid it
Any thoughts? 
(editing source file and forcing useDivWrapper=true, the connections seems work fine and it resolves my issue)

there is an issue containing these workaround https://github.com/niklasvh/html2canvas/issues/1179 but I think it would be better to have a clean solution

**Comment by sporritt** [comment]
We ended up publishing a patched version of html2canvas because the SVG wrap issue seemed like a bug.  There's a post about it (Toolkit edition, but it will work with Community edition) here:

https://jsplumbtoolkit.com/blog/2024/05/17/jsplumb-and-html2canvas
